/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import javax.swing.JPanel;
import Business.EcoSystem;
import javax.swing.JOptionPane;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import Business.Role.Role;
import Business.Employee.Employee;
import Business.Employee.EmployeeDirectory;
import Business.Role.AdminRole;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.Customer.CustomerDirectory;
import java.awt.CardLayout;
/**
 *
 * @author ABHI
 */
public class addResturantJPanel extends javax.swing.JPanel {

    
    public  RestaurantDirectory restaurantDirectory;
    public JPanel container;
    public  EcoSystem sys;
     public DeliveryManDirectory deliveryManDirectory;
     public CustomerDirectory customerDirectory;
    /**
     * Creates new form addResturantJPanel
     */
    public addResturantJPanel(JPanel container, EcoSystem sys,RestaurantDirectory restaurantDirectory,CustomerDirectory customerDirectory,DeliveryManDirectory deliveryManDirectory) {
        initComponents();
        this.container = container;
        this.sys = sys;
        this.restaurantDirectory = restaurantDirectory;
        this.deliveryManDirectory = deliveryManDirectory;
        this.customerDirectory = customerDirectory;
//        restaurantDirectory.deleteRestaurant();
//        sys.setRestaurantDirectory(this.restaurantDirectory=restaurantDirectory);
        
        DefaultTableModel mdl =  (DefaultTableModel) jTable1.getModel();
        Object[] row = new Object[5];
       // RestaurantDirectory re = restaurantDirectory.getResturantDirectory();
        for(int i=0;i<restaurantDirectory.getResturantDirectory().size();i++)
        { Restaurant re = restaurantDirectory.getResturantDirectory().get(i);
         row[3] = re.getUserId();
         row[0] = re.getResturantName();
         row[1] = re.getResturantAddress();
         row[2] = re.getResturantEmail();
         row[4] = re.getId();
         mdl.addRow(row);
        System.out.println(re.getResturantName());
        System.out.println(re.getResturantAddress());
        System.out.println(re.getResturantEmail());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resturantNamejLabel = new javax.swing.JLabel();
        restuarantAddressjLabel = new javax.swing.JLabel();
        restuarantEmailjLabel = new javax.swing.JLabel();
        restuarantNamejTextField = new javax.swing.JTextField();
        restuarantAddressTextField = new javax.swing.JTextField();
        restuarantEmailjTextField = new javax.swing.JTextField();
        userNamejLabel = new javax.swing.JLabel();
        userNamejTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        addRestuarantjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        itemname = new java.awt.Label();
        price = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        resturantNamejLabel.setText("Restuarant Name");

        restuarantAddressjLabel.setText("Restuarant Address");

        restuarantEmailjLabel.setText("Restuarant Email");

        userNamejLabel.setText("UserName");

        jLabel1.setText("Password");

        addRestuarantjButton.setText("Add");
        addRestuarantjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRestuarantjButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RestuarantName", "Restuarant Address", "Restuarant Email", "UserName", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        itemname.setText("Item Name");

        price.setText("Item Price");

        jButton1.setText("addItem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(restuarantAddressjLabel)
                            .addComponent(resturantNamejLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userNamejLabel)
                                .addComponent(restuarantEmailjLabel)
                                .addComponent(jLabel1))
                            .addComponent(jButton2))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNamejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(restuarantNamejTextField)
                            .addComponent(restuarantAddressTextField)
                            .addComponent(restuarantEmailjTextField)
                            .addComponent(jPasswordField))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(itemname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35)
                                            .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(addRestuarantjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(resturantNamejLabel)
                                    .addComponent(restuarantNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(restuarantAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(restuarantAddressjLabel)))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(restuarantEmailjLabel)
                                    .addComponent(restuarantEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(userNamejLabel)
                                    .addComponent(userNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(itemname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(28, 28, 28))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                .addComponent(addRestuarantjButton)
                .addGap(91, 91, 91))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addRestuarantjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRestuarantjButtonActionPerformed
        Restaurant obj = new Restaurant();
        obj.setResturantName(restuarantNamejTextField.getText());
        obj.setResturantAddress(restuarantAddressTextField.getText());
        obj.setResturantEmail(restuarantEmailjTextField.getText());
        RestaurantDirectory obj1 = new RestaurantDirectory();
        
        obj.setUserId(userNamejTextField.getText());
        obj.setMenu(constructMenu());
       // obj1.addRestaurant(obj);
        restaurantDirectory.addRestaurant(obj);
        
        UserAccountDirectory obj2 = new UserAccountDirectory();
        EmployeeDirectory employeedir = new EmployeeDirectory();
        Employee emp = employeedir.createEmployee(userNamejTextField.getText());
        sys.setRestaurantDirectory(restaurantDirectory);
        sys.getUserAccountDirectory().createUserAccount(userNamejTextField.getText(),String.valueOf(jPasswordField.getPassword()), emp,new AdminRole());
       // UserAccount user = obj2.createUserAccount(userNamejTextField.getText(),String.valueOf(jPasswordField.getPassword()), empval,new AdminRole());
        
        
        JOptionPane.showMessageDialog(this,"The Restuarant data is sucessfully saved");
        
    }//GEN-LAST:event_addRestuarantjButtonActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    DefaultTableModel mdl =  (DefaultTableModel) jTable2.getModel();
        Object[] row = new Object[2];
        row[0] = textField1.getText();
        row[1] = Float.parseFloat(textField2.getText());
        mdl.addRow(row);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          container.remove(this);
           CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRestuarantjButton;
    private java.awt.Label itemname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private java.awt.Label price;
    private javax.swing.JTextField restuarantAddressTextField;
    private javax.swing.JLabel restuarantAddressjLabel;
    private javax.swing.JLabel restuarantEmailjLabel;
    private javax.swing.JTextField restuarantEmailjTextField;
    private javax.swing.JTextField restuarantNamejTextField;
    private javax.swing.JLabel resturantNamejLabel;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private javax.swing.JLabel userNamejLabel;
    private javax.swing.JTextField userNamejTextField;
    // End of variables declaration//GEN-END:variables
private HashMap<String, String> constructMenu()
{   HashMap<String, String> val = new HashMap<String, String>();
    for(int i=0;i<jTable2.getRowCount();i++)
{  val.put(jTable2.getValueAt(i, 0).toString(),jTable2.getValueAt(i, 1).toString());
}
    return val;
}
}
