/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkQueue;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.WorkQueue.WorkRequest;
import Business.DeliveryMan.DeliveryManDirectory;
import java.awt.CardLayout;
import Business.DeliveryMan.DeliveryMan;
/**
 *
 * @author ABHI
 */
public class manageOrdersJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    EcoSystem sys;
    private UserAccount userAccount;
    RestaurantDirectory restdir;
    private WorkQueue queue;
    private CustomerDirectory cust;
    private String Restuarantname;
    private DeliveryManDirectory deliverdir;
    /**
     * Creates new form manageOrdersJPanel
     */
    public manageOrdersJPanel(JPanel userProcessContainer, UserAccount account, RestaurantDirectory restdir, WorkQueue queue, EcoSystem sys, String restname,DeliveryManDirectory deliverdir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.sys= sys;
        this.userAccount= account;
        this.restdir = restdir;
        this.queue = queue;
        this.Restuarantname = restname;
        this.deliverdir = deliverdir;
        DefaultTableModel mdl =  (DefaultTableModel) manageOrderjTable.getModel();
        Object[] row = new Object[5];
        //queue.getWorkqueue();
        for(int i=0;i<queue.getWorkqueue().size();i++)
        { 
            WorkRequest re = queue.getWorkqueue().get(i);
       // System.out.println("It is coming home"+re.getStatus());
        String ord = "Ordered";
        if(re.getRestuarantName().equals(restname))
        {
            if(re.getStatus().equalsIgnoreCase(ord))
            {    
//                System.out.println("It is coming home");
                row[0] = re.getOrderNo();
              row[1] = re.getCustomerName();
              row[2] = re.getStatus();
              row[3] = re.getRequestDate();
              row[4] = re.getOrderMenu().keySet().toString();
              mdl.addRow(row);
            }
        }
        }
        
            for(int i=0;i<deliverdir.getDeliveryManDirectory().size();i++)
        { DeliveryMan del = new DeliveryMan();
            del = deliverdir.getDeliveryManDirectory().get(i);
            
            if(del.getQueue()==null)
            { jComboBox1.setSelectedItem(del.getName());
            }
            else if(del.getQueue().getWorkqueue().get(i).getStatus()==null)
            { 
                jComboBox1.setSelectedItem(del.getName());
            }
        }
    loadTable(restname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageOrderjTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        manageOrderjTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        manageOrderjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderNumber", "customerName", "status", "Order Placed Date", "items"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageOrderjTable);

        jButton2.setText("Accept Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        manageOrderjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderNumber", "customerName", "status", "Order Placed Date", "items"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(manageOrderjTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Pending Orders");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Assign to Delivery Person");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(281, 281, 281)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton3))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     loadTable(Restuarantname);
        int k = manageOrderjTable.getSelectedRow();
     System.out.println(k);
     manageOrderjTable.setValueAt("Accepted", k, 2);
     for(int i=0;i<queue.getWorkqueue().size();i++)
        { if(manageOrderjTable.getValueAt(k, 0).equals(queue.getWorkqueue().get(i).getOrderNo()))
            queue.getWorkqueue().get(i).setStatus("Accepted");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      AdminWorkAreaJPanel adminpanel = new AdminWorkAreaJPanel(userProcessContainer,sys,restdir,userAccount,queue,deliverdir);
      userProcessContainer.add("admin",adminpanel);
        CardLayout lay = (CardLayout) userProcessContainer.getLayout();
        lay.next(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    
    }//GEN-LAST:event_jComboBox1ActionPerformed
 private void loadTable(String restname)
 {          DefaultTableModel mdl =  (DefaultTableModel) manageOrderjTable1.getModel();
        Object[] row = new Object[5];
        //queue.getWorkqueue();
        for(int i=0;i<queue.getWorkqueue().size();i++)
        { 
            WorkRequest re = queue.getWorkqueue().get(i);
       // System.out.println("It is coming home"+re.getStatus());
        String ord = "Accepted";
        if(re.getRestuarantName().equals(restname))
        { System.out.println(re.getStatus()+"its coming home");
            if(re.getStatus().equalsIgnoreCase(ord))
            {    
              System.out.println("It is coming home");
                row[0] = re.getOrderNo();
              row[1] = re.getCustomerName();
              row[2] = re.getStatus();
              row[3] = re.getRequestDate();
              row[4] = re.getOrderMenu().keySet().toString();
              mdl.addRow(row);
            }
        }
        }
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable manageOrderjTable;
    private javax.swing.JTable manageOrderjTable1;
    // End of variables declaration//GEN-END:variables
}
